//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.29 at 02:53:46 AM EDT 
//


package edu.umd.cs.guitar.model.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComponentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComponentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Attributes" type="{}AttributesType"/>
 *         &lt;element name="Optional" type="{}AttributesType" minOccurs="0"/>
 *         &lt;element name="EventContext" type="{}EventContextType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComponentType", propOrder = {
    "attributes",
    "optional",
    "eventContext"
})
public class ComponentType {

    @XmlElement(name = "Attributes", required = true)
    protected AttributesType attributes;
    @XmlElement(name = "Optional")
    protected AttributesType optional;
    @XmlElement(name = "EventContext")
    protected List<EventContextType> eventContext;

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link AttributesType }
     *     
     */
    public AttributesType getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributesType }
     *     
     */
    public void setAttributes(AttributesType value) {
        this.attributes = value;
    }

    /**
     * Gets the value of the optional property.
     * 
     * @return
     *     possible object is
     *     {@link AttributesType }
     *     
     */
    public AttributesType getOptional() {
        return optional;
    }

    /**
     * Sets the value of the optional property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributesType }
     *     
     */
    public void setOptional(AttributesType value) {
        this.optional = value;
    }

    /**
     * Gets the value of the eventContext property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventContext property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventContext().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventContextType }
     * 
     * 
     */
    public List<EventContextType> getEventContext() {
        if (eventContext == null) {
            eventContext = new ArrayList<EventContextType>();
        }
        return this.eventContext;
    }

    /**
     * Sets the value of the eventContext property.
     * 
     * @param eventContext
     *     allowed object is
     *     {@link EventContextType }
     *     
     */
    public void setEventContext(List<EventContextType> eventContext) {
        this.eventContext = eventContext;
    }

}
