//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.29 at 02:53:46 AM EDT 
//


package edu.umd.cs.guitar.model.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventContextPatternType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventContextPatternType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MainComponentList" type="{}ComponentListType"/>
 *         &lt;element name="ContextFullEventList" type="{}FullEventListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventContextPatternType", propOrder = {
    "mainComponentList",
    "contextFullEventList"
})
public class EventContextPatternType {

    @XmlElement(name = "MainComponentList", required = true)
    protected ComponentListType mainComponentList;
    @XmlElement(name = "ContextFullEventList", required = true)
    protected FullEventListType contextFullEventList;

    /**
     * Gets the value of the mainComponentList property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentListType }
     *     
     */
    public ComponentListType getMainComponentList() {
        return mainComponentList;
    }

    /**
     * Sets the value of the mainComponentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentListType }
     *     
     */
    public void setMainComponentList(ComponentListType value) {
        this.mainComponentList = value;
    }

    /**
     * Gets the value of the contextFullEventList property.
     * 
     * @return
     *     possible object is
     *     {@link FullEventListType }
     *     
     */
    public FullEventListType getContextFullEventList() {
        return contextFullEventList;
    }

    /**
     * Sets the value of the contextFullEventList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullEventListType }
     *     
     */
    public void setContextFullEventList(FullEventListType value) {
        this.contextFullEventList = value;
    }

}
