//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.29 at 02:53:46 AM EDT 
//


package edu.umd.cs.guitar.model.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FullEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FullEventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WidgetId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FullComponent" type="{}FullComponentType"/>
 *         &lt;element name="Action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ParameterList" type="{}ParameterListType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FullEventType", propOrder = {
    "widgetId",
    "fullComponent",
    "action",
    "parameterList"
})
public class FullEventType {

    @XmlElement(name = "WidgetId", required = true)
    protected String widgetId;
    @XmlElement(name = "FullComponent", required = true)
    protected FullComponentType fullComponent;
    @XmlElement(name = "Action", required = true)
    protected String action;
    @XmlElement(name = "ParameterList")
    protected List<ParameterListType> parameterList;

    /**
     * Gets the value of the widgetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidgetId() {
        return widgetId;
    }

    /**
     * Sets the value of the widgetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidgetId(String value) {
        this.widgetId = value;
    }

    /**
     * Gets the value of the fullComponent property.
     * 
     * @return
     *     possible object is
     *     {@link FullComponentType }
     *     
     */
    public FullComponentType getFullComponent() {
        return fullComponent;
    }

    /**
     * Sets the value of the fullComponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullComponentType }
     *     
     */
    public void setFullComponent(FullComponentType value) {
        this.fullComponent = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the parameterList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameterList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameterList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParameterListType }
     * 
     * 
     */
    public List<ParameterListType> getParameterList() {
        if (parameterList == null) {
            parameterList = new ArrayList<ParameterListType>();
        }
        return this.parameterList;
    }

    /**
     * Sets the value of the parameterList property.
     * 
     * @param parameterList
     *     allowed object is
     *     {@link ParameterListType }
     *     
     */
    public void setParameterList(List<ParameterListType> parameterList) {
        this.parameterList = parameterList;
    }

}
